// <auto-generated />
namespace MvcProjeKampi.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class message_istrue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(message_istrue));
        
        string IMigrationMetadata.Id
        {
            get { return "202106041647039_message_istrue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
